---

- name: Add stable Docker repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker engine
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: Create Docker config directory
  ansible.builtin.file:
    path: /etc/docker/
    state: directory

- name: Create Docker config file
  ansible.builtin.template:
    src: templates/daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - Restart docker service

- name: Start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
